const countries = [
    { code: "CL", name: "Chile", color: "#D32F2F" },
    { code: "CO", name: "Colombia", color: "#FF9800" },
    { code: "CR", name: "Costa Rica", color: "#4CAF50" },
    { code: "EC", name: "Ecuador", color: "#2196F3" },
    { code: "SV", name: "El Salvador", color: "#9C27B0" },
    { code: "GT", name: "Guatemala", color: "#00BCD4" },
    { code: "HN", name: "Honduras", color: "#FFC107" },
    { code: "MX", name: "México", color: "#E91E63" },
    { code: "NI", name: "Nicaragua", color: "#009688" },
    { code: "PA", name: "Panamá", color: "#607D8B" },
    { code: "PE", name: "Perú", color: "#FF5722" }
];

const holidays = [
    { date: "2026-07-13", country: "CO", name: "Día de la Virgen del Carmen", type: "Feriado nacional" },
    { date: "2026-07-16", country: "CL", name: "Virgen del Carmen", type: "Feriado nacional" },
    { date: "2026-07-19", country: "NI", name: "Día de la Revolución Sandinista", type: "Feriado nacional" },
    { date: "2026-07-20", country: "CO", name: "Declaración de Independencia", type: "Feriado nacional" },
    { date: "2026-07-23", country: "PE", name: "Día de la Fuerza Aérea", type: "Feriado nacional no laborable" },
    { date: "2026-07-25", country: "CR", name: "Anexión de Guanacaste", type: "Feriado nacional" },
    { date: "2026-07-28", country: "PE", name: "Fiestas Patrias", type: "Feriado nacional" },
    { date: "2026-07-29", country: "PE", name: "Fiestas Patrias", type: "Feriado nacional" },
    { date: "2026-08-02", country: "CR", name: "Día de la Virgen de los Ángeles", type: "Feriado nacional no laborable" },
    { date: "2026-08-06", country: "PE", name: "Batalla de Junín", type: "Feriado nacional" },
    { date: "2026-08-06", country: "SV", name: "Fiesta de San Salvador", type: "Feriado nacional" },
    { date: "2026-08-07", country: "CO", name: "Batalla de Boyacá", type: "Feriado nacional" },
    { date: "2026-08-11", country: "EC", name: "Primer Grito de la Independencia", type: "Feriado nacional" },
    { date: "2026-08-15", country: "CL", name: "Asunción de la Virgen", type: "Feriado nacional" },
    { date: "2026-08-15", country: "CR", name: "Día de la Madre", type: "Feriado nacional" },
    { date: "2026-08-17", country: "CO", name: "Asunción de la Virgen (traslado)", type: "Feriado nacional" },
    { date: "2026-08-30", country: "PE", name: "Santa Rosa de Lima", type: "Feriado nacional" },
    { date: "2026-08-31", country: "CR", name: "Día del Negro y la Cultura Afrocostarricense", type: "Feriado nacional" },
    { date: "2026-09-14", country: "NI", name: "Batalla de San Jacinto", type: "Feriado nacional" },
    { date: "2026-09-15", country: "CR", name: "Día de la Independencia", type: "Feriado nacional" },
    { date: "2026-09-15", country: "SV", name: "Día de la Independencia", type: "Feriado nacional" },
    { date: "2026-09-15", country: "GT", name: "Día de la Independencia", type: "Feriado nacional" },
    { date: "2026-09-15", country: "HN", name: "Día de la Independencia", type: "Feriado nacional" },
    { date: "2026-09-15", country: "NI", name: "Día de la Independencia", type: "Feriado nacional" },
    { date: "2026-09-16", country: "MX", name: "Día de la Independencia", type: "Feriado nacional" },
    { date: "2026-09-18", country: "CL", name: "Día de la Independencia", type: "Feriado nacional" },
    { date: "2026-09-19", country: "CL", name: "Día de las Glorias del Ejército", type: "Feriado nacional" },
    { date: "2026-10-01", country: "HN", name: "Natalicio de Francisco Morazán", type: "Feriado nacional" },
    { date: "2026-10-02", country: "HN", name: "Día del Descubrimiento de América", type: "Feriado nacional" },
    { date: "2026-10-03", country: "HN", name: "Día del Soldado", type: "Feriado nacional" },
    { date: "2026-10-08", country: "PE", name: "Combate de Angamos", type: "Feriado nacional" },
    { date: "2026-10-09", country: "EC", name: "Independencia de Guayaquil", type: "Feriado nacional" },
    { date: "2026-10-12", country: "CL", name: "Encuentro de Dos Mundos", type: "Feriado nacional" },
    { date: "2026-10-12", country: "CO", name: "Día de la Raza", type: "Feriado nacional" },
    { date: "2026-10-12", country: "MX", name: "Día de la Nación Pluricultural", type: "Feriado cívico" },
    { date: "2026-10-20", country: "GT", name: "Día de la Revolución", type: "Feriado nacional" },
    { date: "2026-10-31", country: "CL", name: "Día de las Iglesias Evangélicas", type: "Feriado nacional" },
    { date: "2026-11-01", country: "CL", name: "Día de Todos los Santos", type: "Feriado nacional" },
    { date: "2026-11-01", country: "GT", name: "Día de Todos los Santos", type: "Feriado nacional" },
    { date: "2026-11-01", country: "PE", name: "Día de Todos los Santos", type: "Feriado nacional" },
    { date: "2026-11-02", country: "CO", name: "Día de Todos los Santos (traslado)", type: "Feriado nacional" },
    { date: "2026-11-02", country: "EC", name: "Día de los Difuntos", type: "Feriado nacional" },
    { date: "2026-11-02", country: "SV", name: "Día de los Difuntos", type: "Feriado nacional" },
    { date: "2026-11-02", country: "MX", name: "Día de Muertos", type: "Feriado festivo" },
    { date: "2026-11-03", country: "EC", name: "Independencia de Cuenca", type: "Feriado nacional" },
    { date: "2026-11-03", country: "PA", name: "Separación de Colombia", type: "Feriado nacional" },
    { date: "2026-11-05", country: "PA", name: "Día de Colón", type: "Feriado nacional" },
    { date: "2026-11-08", country: "NI", name: "Día del Comandante Carlos Fonseca Amador", type: "Feriado nacional" },
    { date: "2026-11-09", country: "NI", name: "Día del Comandante Carlos Fonseca Amador (traslado)", type: "Feriado nacional" },
    { date: "2026-11-10", country: "PA", name: "Primer Grito de Independencia de Los Santos", type: "Feriado nacional" },
    { date: "2026-11-16", country: "CO", name: "Independencia de Cartagena (traslado)", type: "Feriado nacional" },
    { date: "2026-11-16", country: "MX", name: "Día de la Revolución", type: "Feriado nacional" },
    { date: "2026-11-28", country: "PA", name: "Día de la Independencia", type: "Feriado nacional" },
    { date: "2026-12-01", country: "CR", name: "Día de la Abolición del Ejército", type: "Feriado nacional no laborable" },
    { date: "2026-12-08", country: "CL", name: "Día de la Inmaculada Concepción", type: "Feriado nacional" },
    { date: "2026-12-08", country: "CO", name: "Día de la Inmaculada Concepción", type: "Feriado nacional" },
    { date: "2026-12-08", country: "NI", name: "Día de la Inmaculada Concepción", type: "Feriado nacional" },
    { date: "2026-12-08", country: "PA", name: "Día de la Madre", type: "Feriado nacional" },
    { date: "2026-12-08", country: "PE", name: "Día de la Inmaculada Concepción", type: "Feriado nacional" },
    { date: "2026-12-09", country: "PE", name: "Batalla de Ayacucho", type: "Feriado nacional" },
    { date: "2026-12-12", country: "MX", name: "Día de la Virgen de Guadalupe", type: "Feriado festivo" },
    { date: "2026-12-20", country: "PA", name: "Día de Duelo Nacional", type: "Feriado nacional" },
    { date: "2026-12-24", country: "SV", name: "Nochebuena", type: "Feriado nacional" },
    { date: "2026-12-24", country: "GT", name: "Nochebuena (medio día)", type: "Feriado nacional" },
    { date: "2026-12-25", country: "CL", name: "Navidad", type: "Feriado nacional" },
    { date: "2026-12-25", country: "CO", name: "Navidad", type: "Feriado nacional" },
    { date: "2026-12-25", country: "CR", name: "Navidad", type: "Feriado nacional" },
    { date: "2026-12-25", country: "EC", name: "Navidad", type: "Feriado nacional" },
    { date: "2026-12-25", country: "SV", name: "Navidad", type: "Feriado nacional" },
    { date: "2026-12-25", country: "GT", name: "Navidad", type: "Feriado nacional" },
    { date: "2026-12-25", country: "HN", name: "Navidad", type: "Feriado nacional" },
    { date: "2026-12-25", country: "MX", name: "Navidad", type: "Feriado nacional" },
    { date: "2026-12-25", country: "NI", name: "Navidad", type: "Feriado nacional" },
    { date: "2026-12-25", country: "PA", name: "Navidad", type: "Feriado nacional" },
    { date: "2026-12-25", country: "PE", name: "Navidad", type: "Feriado nacional" },
    { date: "2026-12-31", country: "SV", name: "Año Viejo", type: "Feriado nacional" },
    { date: "2026-12-31", country: "GT", name: "Año Viejo (medio día)", type: "Feriado nacional" }
];
